# Criar workflow para rodar os testes
name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.rst'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/*.rst'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Copy .env-EXAMPLE to .env
      run: cp .env-EXAMPLE .env

    - name: Install dependencies
      run: uv sync --group test

    - name: Run tests
      run: |
        uv run pytest --cov=src --cov-report=xml --maxfail=1 --disable-warnings -q

    - name: Upload coverage report
      if: matrix.python-version == '3.13'
      uses: codecov/codecov-action@v5
      with:
        files: coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
